# This is the configuration used to check the rubocop source code.


AllCops:
  Exclude:
    - 'config/**/*'
    - 'app/main/config/**/*'
    - 'Gemfile'
    - 'app/main/controllers/main_controller.rb'
    - 'app/user_templates/controllers/main_controller.rb'

Documentation:
    Enabled: false
